import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardHeader, CardContent } from './ui/card';
import { Badge } from './ui/badge';
export function DistrictCard({ district, onSelect, tier }) {
    return (_jsxs(Card, { className: `bg-card rounded-lg border border-border transition-all ${onSelect ? 'cursor-pointer hover:shadow-md hover:border-accent' : ''}`, onClick: onSelect, children: [_jsx(CardHeader, { className: "border-b border-border p-4", children: _jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "text-lg font-semibold text-foreground truncate", children: district.name }), _jsxs("p", { className: "text-sm text-muted-foreground mt-1", children: [district.city, ", ", district.state, " \u2022 NCES: ", district.ncesId] })] }), tier && (_jsx(Badge, { variant: tier === 'tier1'
                                ? 'default'
                                : tier === 'tier2'
                                    ? 'secondary'
                                    : 'outline', children: tier.toUpperCase() }))] }) }), _jsxs(CardContent, { className: "p-4 space-y-3", children: [district.enrollment && (_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-muted-foreground", children: "Enrollment" }), _jsx("span", { className: "font-medium text-foreground", children: district.enrollment.toLocaleString() })] })), district.gradesServed && (_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-muted-foreground", children: "Grades" }), _jsx("span", { className: "font-medium text-foreground", children: district.gradesServed })] })), district.superintendentName && (_jsxs("div", { className: "pt-2 border-t border-border", children: [_jsx("div", { className: "text-sm text-muted-foreground mb-1", children: "Superintendent" }), _jsx("div", { className: "text-sm font-medium text-foreground", children: district.superintendentName }), district.superintendentEmail && (_jsx("a", { href: `mailto:${district.superintendentEmail}`, className: "text-sm text-blue-600 dark:text-blue-400 hover:underline", onClick: (e) => e.stopPropagation(), children: district.superintendentEmail }))] })), (district.frplPercent || district.minorityPercent) && (_jsxs("div", { className: "pt-2 border-t border-border space-y-2", children: [district.frplPercent && (_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-muted-foreground", children: "FRPL %" }), _jsxs("span", { className: "font-medium text-foreground", children: [parseFloat(district.frplPercent).toFixed(1), "%"] })] })), district.minorityPercent && (_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-muted-foreground", children: "Minority %" }), _jsxs("span", { className: "font-medium text-foreground", children: [parseFloat(district.minorityPercent).toFixed(1), "%"] })] }))] })), district.websiteDomain && (_jsx("div", { className: "pt-2 border-t border-border", children: _jsx("a", { href: `https://${district.websiteDomain}`, target: "_blank", rel: "noopener noreferrer", className: "text-sm text-blue-600 dark:text-blue-400 hover:underline", onClick: (e) => e.stopPropagation(), children: district.websiteDomain }) }))] })] }));
}
